/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Anthropic-inspired palette: warm cream + coral
        surface: '#F5F4EE',
        'surface-dim': '#E9E7DE',
        'surface-bright': '#FBFAF6',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F0EEE6',
        'surface-container': '#E9E7DE',
        'surface-container-high': '#DEDCD3',
        'surface-container-highest': '#D2CFC5',
        'on-surface': '#1F1F1F',
        'on-surface-variant': '#5B5B57',
        'inverse-surface': '#2A2926',
        'inverse-on-surface': '#F5F4EE',
        outline: '#929289',
        'outline-variant': '#D6D4CB',
        'surface-tint': '#D97757',
        primary: '#B65E42',
        'on-primary': '#FFFFFF',
        'primary-container': '#D97757',
        'on-primary-container': '#FFFFFF',
        'inverse-primary': '#F0BC94',
        secondary: '#B65E42',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#F0BC94',
        'on-secondary-container': '#4D1F0A',
        tertiary: '#2A2926',
        'on-tertiary': '#F5F4EE',
        'tertiary-container': '#3C3A34',
        'on-tertiary-container': '#E1DED4',
        error: '#B3261E',
        'on-error': '#FFFFFF',
        'error-container': '#F9DEDC',
        'on-error-container': '#410E0B',
        'primary-fixed': '#F7DDC7',
        'primary-fixed-dim': '#F0BC94',
        'on-primary-fixed': '#4D1F0A',
        'on-primary-fixed-variant': '#6B2E14',
        'secondary-fixed': '#F0DFC8',
        'secondary-fixed-dim': '#DDC2A0',
        'on-secondary-fixed': '#3E2412',
        'on-secondary-fixed-variant': '#6B4127',
        background: '#F5F4EE',
        'on-background': '#1F1F1F',
        'surface-variant': '#E9E7DE',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        glass: '0 4px 24px 0 rgba(31, 31, 31, 0.05)',
        'glass-lg': '0 8px 32px -4px rgba(31, 31, 31, 0.08)',
        'wine-halo': '0 4px 20px -2px rgba(217, 119, 87, 0.35)',
        'wine-deep': '0 20px 50px -10px rgba(77, 31, 10, 0.35)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
